// 東京メトロと都営地下鉄の全駅データです。
const stations = [
    { name: '青山一丁目', ruby: 'あおやまいっちょうめ', line: '銀座線, 半蔵門線, 都営大江戸線' },
    { name: '赤坂', ruby: 'あかさか', line: '千代田線' },
    { name: '赤坂見附', ruby: 'あかさかみつけ', line: '銀座線, 丸ノ内線' },
    { name: '赤羽岩淵', ruby: 'あかばねいわぶち', line: '南北線' },
    { name: '秋葉原', ruby: 'あきはばら', line: '日比谷線' },
    { name: '浅草', ruby: 'あさくさ', line: '銀座線, 都営浅草線' },
    { name: '麻布十番', ruby: 'あざぶじゅうばん', line: '南北線, 都営大江戸線' },
    { name: '綾瀬', ruby: 'あやせ', line: '千代田線' },
    { name: '淡路町', ruby: 'あわじちょう', line: '丸ノ内線' },
    { name: '飯田橋', ruby: 'いいだばし', line: '南北線, 東西線, 有楽町線, 都営大江戸線' },
    { name: '池袋', ruby: 'いけぶくろ', line: '副都心線, 丸ノ内線, 有楽町線' },
    { name: '市ケ谷', ruby: 'いちがや', line: '南北線, 有楽町線, 都営新宿線' },
    { name: '稲荷町', ruby: 'いなりちょう', line: '銀座線' },
    { name: '入谷', ruby: 'いりや', line: '日比谷線' },
    { name: '上野', ruby: 'うえの', line: '銀座線, 日比谷線' },
    { name: '上野広小路', ruby: 'うえのひろこうじ', line: '銀座線' },
    { name: '浦安', ruby: 'うらやす', line: '東西線' },
    { name: '江戸川橋', ruby: 'えどがわばし', line: '有楽町線' },
    { name: '恵比寿', ruby: 'えびす', line: '日比谷線' },
    { name: '王子', ruby: 'おうじ', line: '南北線' },
    { name: '王子神谷', ruby: 'おうじかみや', line: '南北線' },
    { name: '大手町', ruby: 'おおてまち', line: '千代田線, 丸ノ内線, 東西線, 半蔵門線, 都営三田線' },
    { name: '荻窪', ruby: 'おぎくぼ', line: '丸ノ内線' },
    { name: '押上', ruby: 'おしあげ', line: '半蔵門線, 都営浅草線' },
    { name: '落合', ruby: 'おちあい', line: '東西線' },
    { name: '御茶ノ水', ruby: 'おちゃのみず', line: '丸ノ内線' },
    { name: '表参道', ruby: 'おもてさんどう', line: '千代田線, 銀座線, 半蔵門線' },
    { name: '神楽坂', ruby: 'かぐらざか', line: '東西線' },
    { name: '葛西', ruby: 'かさい', line: '東西線' },
    { name: '霞ケ関', ruby: 'かすみがせき', line: '千代田線, 日比谷線, 丸ノ内線' },
    { name: '要町', ruby: 'かなめちょう', line: '副都心線, 有楽町線' },
    { name: '神谷町', ruby: 'かみやちょう', line: '日比谷線' },
    { name: '茅場町', ruby: 'かやばちょう', line: '日比谷線, 東西線' },
    { name: '神田', ruby: 'かんだ', line: '銀座線' },
    { name: '外苑前', ruby: 'がいえんまえ', line: '銀座線' },
    { name: '北綾瀬', ruby: 'きたあやせ', line: '千代田線' },
    { name: '北参道', ruby: 'きたさんどう', line: '副都心線' },
    { name: '北千住', ruby: 'きたせんじゅ', line: '千代田線, 日比谷線' },
    { name: '木場', ruby: 'きば', line: '東西線' },
    { name: '京橋', ruby: 'きょうばし', line: '銀座線' },
    { name: '清澄白河', ruby: 'きよすみしらかわ', line: '半蔵門線, 都営大江戸線' },
    { name: '錦糸町', ruby: 'きんしちょう', line: '半蔵門線' },
    { name: '行徳', ruby: 'ぎょうとく', line: '東西線' },
    { name: '銀座', ruby: 'ぎんざ', line: '銀座線, 日比谷線, 丸ノ内線' },
    { name: '銀座一丁目', ruby: 'ぎんざいっちょうめ', line: '有楽町線' },
    { name: '九段下', ruby: 'くだんした', line: '東西線, 半蔵門線, 都営新宿線' },
    { name: '麴町', ruby: 'こうじまち', line: '有楽町線' },
    { name: '後楽園', ruby: 'こうらくえん', line: '丸ノ内線, 南北線' },
    { name: '小竹向原', ruby: 'こたけむかいはら', line: '副都心線, 有楽町線' },
    { name: '国会議事堂前', ruby: 'こっかいぎじどうまえ', line: '千代田線, 丸ノ内線' },
    { name: '小伝馬町', ruby: 'こでんまちょう', line: '日比谷線' },
    { name: '駒込', ruby: 'こまごめ', line: '南北線' },
    { name: '護国寺', ruby: 'ごこくじ', line: '有楽町線' },
    { name: '桜田門', ruby: 'さくらだもん', line: '有楽町線' },
    { name: '渋谷', ruby: 'しぶや', line: '副都心線, 銀座線, 半蔵門線' },
    { name: '志茂', ruby: 'しも', line: '南北線' },
    { name: '白金高輪', ruby: 'しろかねたかなわ', line: '南北線, 都営三田線' },
    { name: '白金台', ruby: 'しろかねだい', line: '南北線, 都営三田線' },
    { name: '新大塚', ruby: 'しんおおつか', line: '丸ノ内線' },
    { name: '新御茶ノ水', ruby: 'しんおちゃのみず', line: '千代田線' },
    { name: '新木場', ruby: 'しんきば', line: '有楽町線' },
    { name: '新高円寺', ruby: 'しんこうえんじ', line: '丸ノ内線' },
    { name: '新宿', ruby: 'しんじゅく', line: '丸ノ内線, 都営大江戸線, 都営新宿線' },
    { name: '新宿御苑前', ruby: 'しんじゅくぎょえんまえ', line: '丸ノ内線' },
    { name: '新宿三丁目', ruby: 'しんじゅくさんちょうめ', line: '副都心線, 丸ノ内線, 都営新宿線' },
    { name: '新富町', ruby: 'しんとみちょう', line: '有楽町線' },
    { name: '新中野', ruby: 'しんなかの', line: '丸ノ内線' },
    { name: '新橋', ruby: 'しんばし', line: '銀座線, 都営浅草線' },
    { name: '神保町', ruby: 'じんぼうちょう', line: '半蔵門線, 都営新宿線, 都営三田線' },
    { name: '水天宮前', ruby: 'すいてんぐうまえ', line: '半蔵門線' },
    { name: '末広町', ruby: 'すえひろちょう', line: '銀座線' },
    { name: '住吉', ruby: 'すみよし', line: '半蔵門線, 都営新宿線' },
    { name: '千川', ruby: 'せんかわ', line: '副都心線, 有楽町線' },
    { name: '千駄木', ruby: 'せんだぎ', line: '千代田線' },
    { name: '雑司が谷', ruby: 'ぞうしがや', line: '副都心線' },
    { name: '高田馬場', ruby: 'たかだのばば', line: '東西線' },
    { name: '竹橋', ruby: 'たけばし', line: '東西線' },
    { name: '辰巳', ruby: 'たつみ', line: '有楽町線' },
    { name: '溜池山王', ruby: 'ためいけさんのう', line: '銀座線, 南北線' },
    { name: '田原町', ruby: 'たわらまち', line: '銀座線' },
    { name: '地下鉄赤塚', ruby: 'ちかてつあかつか', line: '副都心線, 有楽町線' },
    { name: '地下鉄成増', ruby: 'ちかてつなります', line: '副都心線, 有楽町線' },
    { name: '月島', ruby: 'つきしま', line: '有楽町線, 都営大江戸線' },
    { name: '築地', ruby: 'つきじ', line: '日比谷線' },
    { name: '東京', ruby: 'とうきょう', line: '丸ノ内線' },
    { name: '東大前', ruby: 'とうだいまえ', line: '南北線' },
    { name: '東陽町', ruby: 'とうようちょう', line: '東西線' },
    { name: '豊洲', ruby: 'とよす', line: '有楽町線' },
    { name: '虎ノ門', ruby: 'とらのもん', line: '銀座線' },
    { name: '虎ノ門ヒルズ', ruby: 'とらのもんひるず', line: '日比谷線' },
    { name: '仲御徒町', ruby: 'なかおかちまち', line: '日比谷線' },
    { name: '中野', ruby: 'なかの', line: '東西線' },
    { name: '中野坂上', ruby: 'なかのさかうえ', line: '丸ノ内線, 都営大江戸線' },
    { name: '中野新橋', ruby: 'なかのしんばし', line: '丸ノ内線' },
    { name: '中野富士見町', ruby: 'なかのふじみちょう', line: '丸ノ内線' },
    { name: '中目黒', ruby: 'なかめぐろ', line: '日比谷線' },
    { name: '永田町', ruby: 'ながたちょう', line: '南北線, 有楽町線, 半蔵門線' },
    { name: '西葛西', ruby: 'にしかさい', line: '東西線' },
    { name: '西ケ原', ruby: 'にしがはら', line: '南北線' },
    { name: '西新宿', ruby: 'にししんじゅく', line: '丸ノ内線' },
    { name: '西日暮里', ruby: 'にしにっぽり', line: '千代田線' },
    { name: '西船橋', ruby: 'にしふなばし', line: '東西線' },
    { name: '西早稲田', ruby: 'にしわせだ', line: '副都心線' },
    { name: '二重橋前', ruby: 'にじゅうばしまえ', line: '千代田線' },
    { name: '日本橋', ruby: 'にほんばし', line: '銀座線, 東西線, 都営浅草線' },
    { name: '人形町', ruby: 'にんぎょうちょう', line: '日比谷線, 都営浅草線' },
    { name: '根津', ruby: 'ねづ', line: '千代田線' },
    { name: '乃木坂', ruby: 'のぎざか', line: '千代田線' },
    { name: '八丁堀', ruby: 'はっちょうぼり', line: '日比谷線' },
    { name: '半蔵門', ruby: 'はんぞうもん', line: '半蔵門線' },
    { name: '原木中山', ruby: 'ばらきなかやま', line: '東西線' },
    { name: '氷川台', ruby: 'ひかわだい', line: '副都心線, 有楽町線' },
    { name: '東池袋', ruby: 'ひがしいけぶくろ', line: '有楽町線' },
    { name: '東銀座', ruby: 'ひがしぎんざ', line: '日比谷線, 都営浅草線' },
    { name: '東高円寺', ruby: 'ひがしこうえんじ', line: '丸ノ内線' },
    { name: '東新宿', ruby: 'ひがししんじゅく', line: '副都心線, 都営大江戸線' },
    { name: '日比谷', ruby: 'ひびや', line: '千代田線, 日比谷線, 都営三田線' },
    { name: '広尾', ruby: 'ひろお', line: '日比谷線' },
    { name: '平和台', ruby: 'へいわだい', line: '副都心線, 有楽町線' },
    { name: '方南町', ruby: 'ほうなんちょう', line: '丸ノ内線' },
    { name: '本駒込', ruby: 'ほんこまごめ', line: '南北線' },
    { name: '本郷三丁目', ruby: 'ほんごうさんちょうめ', line: '丸ノ内線, 都営大江戸線' },
    { name: '町屋', ruby: 'まちや', line: '千代田線' },
    { name: '三越前', ruby: 'みつこしまえ', line: '銀座線, 半蔵門線' },
    { name: '南阿佐ケ谷', ruby: 'みなみあさがや', line: '丸ノ内線' },
    { name: '南行徳', ruby: 'みなみぎょうとく', line: '東西線' },
    { name: '南砂町', ruby: 'みなみすなまち', line: '東西線' },
    { name: '南千住', ruby: 'みなみせんじゅ', line: '日比谷線' },
    { name: '三ノ輪', ruby: 'みのわ', line: '日比谷線' },
    { name: '茗荷谷', ruby: 'みょうがだに', line: '丸ノ内線' },
    { name: '妙典', ruby: 'みょうでん', line: '東西線' },
    { name: '明治神宮前', ruby: 'めいじじんぐうまえ', line: '千代田線, 副都心線' },
    { name: '目黒', ruby: 'めぐろ', line: '南北線, 都営三田線' },
    { name: '門前仲町', ruby: 'もんぜんなかちょう', line: '東西線, 都営大江戸線' },
    { name: '有楽町', ruby: 'ゆうらくちょう', line: '有楽町線' },
    { name: '湯島', ruby: 'ゆしま', line: '千代田線' },
    { name: '四ツ谷', ruby: 'よつや', line: '丸ノ内線, 南北線' },
    { name: '四谷三丁目', ruby: 'よつやさんちょうめ', line: '丸ノ内線' },
    { name: '代々木上原', ruby: 'よよぎうえはら', line: '千代田線' },
    { name: '代々木公園', ruby: 'よよぎこうえん', line: '千代田線' },
    { name: '六本木', ruby: 'ろっぽんぎ', line: '日比谷線, 都営大江戸線' },
    { name: '六本木一丁目', ruby: 'ろっぽんぎいっちょうめ', line: '南北線' },
    { name: '和光市', ruby: 'わこうし', line: '副都心線, 有楽町線' },
    { name: '早稲田', ruby: 'わせだ', line: '東西線' },
    { name: '西馬込', ruby: 'にしまごめ', line: '都営浅草線' },
    { name: '馬込', ruby: 'まごめ', line: '都営浅草線' },
    { name: '中延', ruby: 'なかのぶ', line: '都営浅草線' },
    { name: '戸越', ruby: 'とごし', line: '都営浅草線' },
    { name: '五反田', ruby: 'ごたんだ', line: '都営浅草線' },
    { name: '高輪台', ruby: 'たかなわだい', line: '都営浅草線' },
    { name: '泉岳寺', ruby: 'せんがくじ', line: '都営浅草線' },
    { name: '三田', ruby: 'みた', line: '都営三田線, 都営浅草線' },
    { name: '大門', ruby: 'だいもん', line: '都営大江戸線, 都営浅草線' },
    { name: '宝町', ruby: 'たからちょう', line: '都営浅草線' },
    { name: '東日本橋', ruby: 'ひがしにほんばし', line: '都営浅草線' },
    { name: '浅草橋', ruby: 'あさくさばし', line: '都営浅草線' },
    { name: '蔵前', ruby: 'くらまえ', line: '都営大江戸線, 都営浅草線' },
    { name: '本所吾妻橋', ruby: 'ほんじょあづまばし', line: '都営浅草線' },
    { name: '芝公園', ruby: 'しばこうえん', line: '都営三田線' },
    { name: '御成門', ruby: 'おなりもん', line: '都営三田線' },
    { name: '内幸町', ruby: 'うちさいわいちょう', line: '都営三田線' },
    { name: '水道橋', ruby: 'すいどうばし', line: '都営三田線' },
    { name: '春日', ruby: 'かすが', line: '都営大江戸線, 都営三田線' },
    { name: '白山', ruby: 'はくさん', line: '都営三田線' },
    { name: '千石', ruby: 'せんごく', line: '都営三田線' },
    { name: '巣鴨', ruby: 'すがも', line: '都営三田線' },
    { name: '西巣鴨', ruby: 'にしすがも', line: '都営三田線' },
    { name: '新板橋', ruby: 'しんいたばし', line: '都営三田線' },
    { name: '板橋区役所前', ruby: 'いたばしくやくしょまえ', line: '都営三田線' },
    { name: '板橋本町', ruby: 'いたばしほんちょう', line: '都営三田線' },
    { name: '本蓮沼', ruby: 'もとはすぬま', line: '都営三田線' },
    { name: '志村坂上', ruby: 'しむらさかうえ', line: '都営三田線' },
    { name: '志村三丁目', ruby: 'しむらさんちょうめ', line: '都営三田線' },
    { name: '蓮根', ruby: 'はすね', line: '都営三田線' },
    { name: '西台', ruby: 'にしだい', line: '都営三田線' },
    { name: '高島平', ruby: 'たかしまだいら', line: '都営三田線' },
    { name: '新高島平', ruby: 'しんたかしまだいら', line: '都営三田線' },
    { name: '西高島平', ruby: 'にしたかしまだいら', line: '都営三田線' },
    { name: '曙橋', ruby: 'あけぼのばし', line: '都営新宿線' },
    { name: '小川町', ruby: 'おがわまち', line: '都営新宿線' },
    { name: '岩本町', ruby: 'いわもとちょう', line: '都営新宿線' },
    { name: '馬喰横山', ruby: 'ばくろよこやま', line: '都営新宿線' },
    { name: '浜町', ruby: 'はまちょう', line: '都営新宿線' },
    { name: '森下', ruby: 'もりした', line: '都営大江戸線, 都営新宿線' },
    { name: '菊川', ruby: 'きくかわ', line: '都営新宿線' },
    { name: '西大島', ruby: 'にしおおじま', line: '都営新宿線' },
    { name: '大島', ruby: 'おおじま', line: '都営新宿線' },
    { name: '東大島', ruby: 'ひがしおおじま', line: '都営新宿線' },
    { name: '船堀', ruby: 'ふなぼり', line: '都営新宿線' },
    { name: '一之江', ruby: 'いちのえ', line: '都営新宿線' },
    { name: '瑞江', ruby: 'みずえ', line: '都営新宿線' },
    { name: '篠崎', ruby: 'しのざき', line: '都営新宿線' },
    { name: '本八幡', ruby: 'もとやわた', line: '都営新宿線' },
    { name: '新宿西口', ruby: 'しんじゅくにしぐち', line: '都営大江戸線' },
    { name: '若松河田', ruby: 'わかまつかわだ', line: '都営大江戸線' },
    { name: '牛込柳町', ruby: 'うしごめやなぎちょう', line: '都営大江戸線' },
    { name: '牛込神楽坂', ruby: 'うしごめかぐらざか', line: '都営大江戸線' },
    { name: '上野御徒町', ruby: 'うえのおかちまち', line: '都営大江戸線' },
    { name: '新御徒町', ruby: 'しんおかちまち', line: '都営大江戸線' },
    { name: '両国', ruby: 'りょうごく', line: '都営大江戸線' },
    { name: '勝どき', ruby: 'かちどき', line: '都営大江戸線' },
    { name: '築地市場', ruby: 'つきじしじょう', line: '都営大江戸線' },
    { name: '汐留', ruby: 'しおどめ', line: '都営大江戸線' },
    { name: '赤羽橋', ruby: 'あかばねばし', line: '都営大江戸線' },
    { name: '国立競技場', ruby: 'こくりつきょうぎじょう', line: '都営大江戸線' },
    { name: '代々木', ruby: 'よよぎ', line: '都営大江戸線' },
    { name: '都庁前', ruby: 'とちょうまえ', line: '都営大江戸線' },
    { name: '西新宿五丁目', ruby: 'にししんじゅくごちょうめ', line: '都営大江戸線' },
    { name: '東中野', ruby: 'ひがしなかの', line: '都営大江戸線' },
    { name: '中井', ruby: 'なかい', line: '都営大江戸線' },
    { name: '落合南長崎', ruby: 'おちあいみなみながさき', line: '都営大江戸線' },
    { name: '新江古田', ruby: 'しんえごた', line: '都営大江戸線' },
    { name: '練馬', ruby: 'ねりま', line: '都営大江戸線' },
    { name: '豊島園', ruby: 'としまえん', line: '都営大江戸線' },
    { name: '練馬春日町', ruby: 'ねりまかすがちょう', line: '都営大江戸線' },
    { name: '光が丘', ruby: 'ひかりがおか', line: '都営大江戸線' }
];

// HTMLで用意したボタンと表示場所を取得します。
const generateButton = document.getElementById('generate-button');
const stationNameElement = document.getElementById('station-name');
const stationRubyElement = document.getElementById('station-ruby');
const stationLineElement = document.getElementById('station-line');

// ボタンがクリックされた時に動く処理を書きます。
generateButton.addEventListener('click', () => {
    // 1. 駅リストの長さ（駅の数）を取得します。
    const listLength = stations.length;
    
    // 2. 0から駅の数の間にあるランダムな数字を生成します。
    const randomIndex = Math.floor(Math.random() * listLength);
    
    // 3. ランダムな数字を元に、リストから一つの駅のオブジェクト全体を選びます。
    const randomStation = stations[randomIndex];
    
    // 4. 選んだオブジェクトから、それぞれの情報を取り出してHTMLに表示します。
    stationNameElement.textContent = randomStation.name;
    stationRubyElement.textContent = randomStation.ruby;
    stationLineElement.textContent = `路線: ${randomStation.line}`;
});
